unsigned char _22_clients_sql[4129] = {
"create function sys.password_hash (username string)\n"
"	returns string\n"
"    external name sql.password;\n"
"create function sys.decypher (cypher string)\n"
"	returns string\n"
"    external name sql.decypher;\n"
"create function sys.sessions()\n"
"returns table(\n"
"	\"sessionid\" int,\n"
"	\"username\" string,\n"
"	\"login\" timestamp,\n"
"	\"idle\" timestamp,\n"
"	\"optimizer\" string,\n"
"	\"sessiontimeout\" int,\n"
"	\"querytimeout\" int,\n"
"	\"workerlimit\" int,\n"
"	\"memorylimit\" int,\n"
"	\"language\" string,\n"
"	\"peer\" string,\n"
"	\"hostname\" string,\n"
"	\"application\" string,\n"
"	\"client\" string,\n"
"	\"clientpid\" bigint,\n"
"	\"remark\" string\n"
")\n"
"external name sql.sessions;\n"
"create view sys.sessions as select * from sys.sessions();\n"
"grant select on sys.sessions to public;\n"
"create function sys.unclosed_result_sets()\n"
"returns table(\n"
"	\"query_id\" oid,\n"
"	\"res_id\" int\n"
")\n"
"external name sql.unclosed_result_sets;\n"
"grant execute on function sys.unclosed_result_sets() to public;\n"
"create procedure sys.setclientinfo(property string, value string)\n"
"	external name clients.setinfo;\n"
"grant execute on procedure sys.setclientinfo(string, string) to public;\n"
"create table sys.clientinfo_properties(prop varchar(40) NOT NULL, session_attr varchar(40) NOT NULL);\n"
"insert into sys.clientinfo_properties values\n"
"	('ClientHostname', 'hostname'),\n"
"	('ApplicationName', 'application'),\n"
"	('ClientLibrary', 'client'),\n"
"	('ClientPid', 'clientpid'),\n"
"	('ClientRemark', 'remark');\n"
"alter table sys.clientinfo_properties SET READ ONLY;\n"
"grant select on sys.clientinfo_properties to public;\n"
"create procedure sys.shutdown(delay tinyint)\n"
"	external name sql.shutdown;\n"
"create procedure sys.shutdown(delay tinyint, force bool)\n"
"	external name sql.shutdown;\n"
"create procedure sys.setoptimizer(\"optimizer\" string)\n"
"	external name clients.setoptimizer;\n"
"grant execute on procedure sys.setoptimizer(string) to public;\n"
"create procedure sys.setquerytimeout(\"query\" int)\n"
"	external name clients.setquerytimeout;\n"
"grant execute on procedure sys.setquerytimeout(int) to public;\n"
"create procedure sys.setsessiontimeout(\"timeout\" int)\n"
"	external name clients.setsessiontimeout;\n"
"grant execute on procedure sys.setsessiontimeout(int) to public;\n"
"create procedure sys.setworkerlimit(\"limit\" int)\n"
"	external name clients.setworkerlimit;\n"
"grant execute on procedure sys.setworkerlimit(int) to public;\n"
"create procedure sys.setmemorylimit(\"limit\" int)\n"
"	external name clients.setmemorylimit;\n"
"grant execute on procedure sys.setmemorylimit(int) to public;\n"
"create procedure sys.setoptimizer(\"sessionid\" int, \"optimizer\" string)\n"
"	external name clients.setoptimizer;\n"
"create procedure sys.setquerytimeout(\"sessionid\" int, \"query\" int)\n"
"	external name clients.setquerytimeout;\n"
"create procedure sys.setsessiontimeout(\"sessionid\" int, \"query\" int)\n"
"	external name clients.setsessiontimeout;\n"
"create procedure sys.setworkerlimit(\"sessionid\" int, \"limit\" int)\n"
"	external name clients.setworkerlimit;\n"
"create procedure sys.setmemorylimit(\"sessionid\" int, \"limit\" int)\n"
"	external name clients.setmemorylimit;\n"
"create procedure sys.stopsession(\"sessionid\" int)\n"
"	external name clients.stopsession;\n"
"create procedure sys.setprinttimeout(\"timeout\" integer)\n"
"	external name clients.setprinttimeout;\n"
"create function sys.prepared_statements()\n"
"returns table(\n"
"	\"sessionid\" int,\n"
"	\"username\" string,\n"
"	\"statementid\" int,\n"
"	\"statement\" string,\n"
"	\"created\" timestamp\n"
")\n"
"external name sql.prepared_statements;\n"
"grant execute on function sys.prepared_statements to public;\n"
"create view sys.prepared_statements as select * from sys.prepared_statements();\n"
"grant select on sys.prepared_statements to public;\n"
"create function sys.prepared_statements_args()\n"
"returns table(\n"
"	\"statementid\" int,\n"
"	\"type\" string,\n"
"	\"type_digits\" int,\n"
"	\"type_scale\" int,\n"
"	\"inout\" tinyint,\n"
"	\"number\" int,\n"
"	\"schema\" string,\n"
"	\"table\" string,\n"
"	\"column\" string\n"
")\n"
"external name sql.prepared_statements_args;\n"
"grant execute on function sys.prepared_statements_args to public;\n"
"create view sys.prepared_statements_args as select * from sys.prepared_statements_args();\n"
"grant select on sys.prepared_statements_args to public;\n"
"create function sys.current_sessionid() returns int\n"
"external name clients.current_sessionid;\n"
"grant execute on function sys.current_sessionid to public;\n"
};
#include "monetdb_config.h"
#include "sql_import.h"
#ifdef _MSC_VER
#undef read
#pragma section(".CRT$XCU",read)
#endif
LIB_STARTUP_FUNC(init_22_clients_sql)
{ sql_register("22_clients", _22_clients_sql); }
