unsigned char _26_sysmon_sql[2068] = {
"create function sys.queue()\n"
"returns table(\n"
"	\"tag\" bigint,\n"
"	\"sessionid\" int,\n"
"	\"username\" string,\n"
"	\"started\" timestamp,\n"
"	\"status\" string,\n"
"	\"query\" string,\n"
"	\"finished\" timestamp,\n"
"	\"maxworkers\" int,\n"
"	\"footprint\" int\n"
")\n"
"external name sysmon.queue;\n"
"grant execute on function sys.queue() to public;\n"
"create view sys.queue as select * from sys.queue();\n"
"grant select on sys.queue to public;\n"
"create function sys.queue(username string)\n"
"returns table(\n"
"	\"tag\" bigint,\n"
"	\"sessionid\" int,\n"
"	\"username\" string,\n"
"	\"started\" timestamp,\n"
"	\"status\" string,\n"
"	\"query\" string,\n"
"	\"finished\" timestamp,\n"
"	\"maxworkers\" int,\n"
"	\"footprint\" int\n"
")\n"
"external name sysmon.queue;\n"
"create procedure sys.pause(tag bigint)\n"
"external name sysmon.pause;\n"
"grant execute on procedure sys.pause(bigint) to public;\n"
"create procedure sys.resume(tag bigint)\n"
"external name sysmon.resume;\n"
"grant execute on procedure sys.resume(bigint) to public;\n"
"create procedure sys.stop(tag bigint)\n"
"external name sysmon.stop;\n"
"grant execute on procedure sys.stop(bigint) to public;\n"
"create procedure sys.pause(tag bigint, username string)\n"
"external name sysmon.pause;\n"
"create procedure sys.resume(tag bigint, username string)\n"
"external name sysmon.resume;\n"
"create procedure sys.stop(tag bigint, username string)\n"
"external name sysmon.stop;\n"
"create function sys.user_statistics()\n"
"returns table(\n"
"	username string,\n"
"	querycount bigint,\n"
"	totalticks bigint,\n"
"	started timestamp,\n"
"	finished timestamp,\n"
"	maxticks bigint,\n"
"	maxquery string\n"
")\n"
"external name sysmon.user_statistics;\n"
"create procedure sys.vacuum(sname string, tname string, cname string)\n"
"external name sql.vacuum;\n"
"create procedure sys.vacuum(sname string, tname string, cname string, interval int)\n"
"external name sql.vacuum;\n"
"create procedure sys.stop_vacuum(sname string, tname string, cname string)\n"
"external name sql.stop_vacuum;\n"
"create procedure sys.vacuum(sname string, tname string)\n"
"external name sql.vacuum;\n"
"create procedure sys.vacuum(sname string, tname string, interval int)\n"
"external name sql.vacuum;\n"
"create procedure sys.stop_vacuum(sname string, tname string)\n"
"external name sql.stop_vacuum;\n"
};
#include "monetdb_config.h"
#include "sql_import.h"
#ifdef _MSC_VER
#undef read
#pragma section(".CRT$XCU",read)
#endif
LIB_STARTUP_FUNC(init_26_sysmon_sql)
{ sql_register("26_sysmon", _26_sysmon_sql); }
