unsigned char _44_inet46_sql[3463] = {
"create type inet4 external name inet4;\n"
"create type inet6 external name inet6;\n"
"create function contains(ip1 inet4, ip2 inet4, netmask tinyint)\n"
"	returns bool external name \"inet46\".\"inet4containsinet4\";\n"
"create function contains(ip1 inet4, netmask1 tinyint, ip2 inet4, netmask2 tinyint)\n"
"	returns bool external name \"inet46\".\"inet4containsinet4\";\n"
"create function containsorequal(ip1 inet4, ip2 inet4, netmask tinyint)\n"
"	returns bool external name \"inet46\".\"inet4containsorequalinet4\";\n"
"create function containsorequal(ip1 inet4, netmask1 tinyint, ip2 inet4, netmask2 tinyint)\n"
"	returns bool external name \"inet46\".\"inet4containsorequalinet4\";\n"
"create function containssymmetric(ip1 inet4, netmask1 tinyint, ip2 inet4, netmask2 tinyint)\n"
"	returns bool external name \"inet46\".\"inet4containssymmetricinet4\";\n"
"create function contains(ip1 inet6, ip2 inet6, netmask smallint)\n"
"	returns bool external name \"inet46\".\"inet6containsinet6\";\n"
"create function contains(ip1 inet6, netmask1 smallint, ip2 inet6, netmask2 smallint)\n"
"	returns bool external name \"inet46\".\"inet6containsinet6\";\n"
"create function containsorequal(ip1 inet6, ip2 inet6, netmask smallint)\n"
"	returns bool external name \"inet46\".\"inet6containsorequalinet6\";\n"
"create function containsorequal(ip1 inet6, netmask1 smallint, ip2 inet6, netmask2 smallint)\n"
"	returns bool external name \"inet46\".\"inet6containsorequalinet6\";\n"
"create function containssymmetric(ip1 inet6, netmask1 smallint, ip2 inet6, netmask2 smallint)\n"
"	returns bool external name \"inet46\".\"inet6containssymmetricinet6\";\n"
"create function bit_not(ip1 inet4)\n"
"	returns inet4 external name \"calc\".\"not\";\n"
"create function bit_and(ip1 inet4, ip2 inet4)\n"
"	returns inet4 external name \"calc\".\"and\";\n"
"create function bit_or(ip1 inet4, ip2 inet4)\n"
"	returns inet4 external name \"calc\".\"or\";\n"
"create function bit_xor(ip1 inet4, ip2 inet4)\n"
"	returns inet4 external name \"calc\".\"xor\";\n"
"create function bit_not(ip1 inet6)\n"
"	returns inet6 external name \"calc\".\"not\";\n"
"create function bit_and(ip1 inet6, ip2 inet6)\n"
"	returns inet6 external name \"calc\".\"and\";\n"
"create function bit_or(ip1 inet6, ip2 inet6)\n"
"	returns inet6 external name \"calc\".\"or\";\n"
"create function bit_xor(ip1 inet6, ip2 inet6)\n"
"	returns inet6 external name \"calc\".\"xor\";\n"
"grant execute on function contains(inet4, inet4, tinyint) to public;\n"
"grant execute on function contains(inet4, tinyint, inet4, tinyint) to public;\n"
"grant execute on function containsorequal(inet4, inet4, tinyint) to public;\n"
"grant execute on function containsorequal(inet4, tinyint, inet4, tinyint) to public;\n"
"grant execute on function containssymmetric(inet4, tinyint, inet4, tinyint) to public;\n"
"grant execute on function contains(inet6, inet6, smallint) to public;\n"
"grant execute on function contains(inet6, smallint, inet6, smallint) to public;\n"
"grant execute on function containsorequal(inet6, inet6, smallint) to public;\n"
"grant execute on function containsorequal(inet6, smallint, inet6, smallint) to public;\n"
"grant execute on function containssymmetric(inet6, smallint, inet6, smallint) to public;\n"
"grant execute on function bit_not(inet4) to public;\n"
"grant execute on function bit_and(inet4, inet4) to public;\n"
"grant execute on function bit_or(inet4, inet4) to public;\n"
"grant execute on function bit_xor(inet4, inet4) to public;\n"
"grant execute on function bit_not(inet6) to public;\n"
"grant execute on function bit_and(inet6, inet6) to public;\n"
"grant execute on function bit_or(inet6, inet6) to public;\n"
"grant execute on function bit_xor(inet6, inet6) to public;\n"
};
#include "monetdb_config.h"
#include "sql_import.h"
#ifdef _MSC_VER
#undef read
#pragma section(".CRT$XCU",read)
#endif
LIB_STARTUP_FUNC(init_44_inet46_sql)
{ sql_register("44_inet46", _44_inet46_sql); }
