unsigned char _48_txtsim_sql[2536] = {
"create function sys.levenshtein(x string, y string)\n"
"returns int external name txtsim.levenshtein;\n"
"grant execute on function levenshtein(string, string) to public;\n"
"create function sys.levenshtein(x string, y string, insdel int, rep int)\n"
"returns int external name txtsim.levenshtein;\n"
"grant execute on function levenshtein(string, string, int, int) to public;\n"
"create function sys.levenshtein(x string, y string, insdel int, rep int, trans int)\n"
"returns int external name txtsim.levenshtein;\n"
"grant execute on function levenshtein(string, string, int, int, int) to public;\n"
"create filter function sys.maxlevenshtein(x string, y string, k int)\n"
"external name txtsim.maxlevenshtein;\n"
"grant execute on filter function maxlevenshtein(string, string, int) to public;\n"
"create filter function sys.maxlevenshtein(x string, y string, k int, insdel int, rep int)\n"
"external name txtsim.maxlevenshtein;\n"
"grant execute on filter function maxlevenshtein(string, string, int, int, int) to public;\n"
"create function sys.jarowinkler(x string, y string)\n"
"returns double external name txtsim.jarowinkler;\n"
"grant execute on function jarowinkler(string, string) to public;\n"
"create filter function minjarowinkler(x string, y string, threshold double)\n"
"external name txtsim.minjarowinkler;\n"
"grant execute on filter function minjarowinkler(string, string, double) to public;\n"
"create function sys.dameraulevenshtein(x string, y string)\n"
"returns int external name txtsim.dameraulevenshtein;\n"
"grant execute on function dameraulevenshtein(string, string) to public;\n"
"create function sys.dameraulevenshtein(x string, y string, insdel int, rep int, trans int)\n"
"returns int external name txtsim.dameraulevenshtein;\n"
"grant execute on function dameraulevenshtein(string, string, int, int, int) to public;\n"
"create function sys.editdistance(x string, y string)\n"
"returns int external name txtsim.editdistance;\n"
"grant execute on function editdistance(string, string) to public;\n"
"create function sys.editdistance2(x string, y string)\n"
"returns int external name txtsim.editdistance2;\n"
"grant execute on function editdistance2(string, string) to public;\n"
"create function sys.soundex(x string)\n"
"returns string external name txtsim.soundex;\n"
"grant execute on function soundex(string) to public;\n"
"create function sys.difference(x string, y string)\n"
"returns int external name txtsim.stringdiff;\n"
"grant execute on function difference(string, string) to public;\n"
"create function sys.qgramnormalize(x string)\n"
"returns string external name txtsim.qgramnormalize;\n"
"grant execute on function qgramnormalize(string) to public;\n"
};
#include "monetdb_config.h"
#include "sql_import.h"
#ifdef _MSC_VER
#undef read
#pragma section(".CRT$XCU",read)
#endif
LIB_STARTUP_FUNC(init_48_txtsim_sql)
{ sql_register("48_txtsim", _48_txtsim_sql); }
