unsigned char _49_strings_sql[3758] = {
"create function asciify(x string)\n"
"returns string external name str.asciify;\n"
"grant execute on function asciify(string) to public;\n"
"create function sys.startswith(x string, y string)\n"
"returns boolean external name str.startswith;\n"
"grant execute on function startswith(string, string) to public;\n"
"create function sys.startswith(x string, y string, icase boolean)\n"
"returns boolean external name str.startswith;\n"
"grant execute on function startswith(string, string, boolean) to public;\n"
"create filter function sys.startswith(x string, y string)\n"
"external name str.startswith;\n"
"grant execute on filter function startswith(string, string) to public;\n"
"create filter function sys.startswith(x string, y string, icase boolean)\n"
"external name str.startswith;\n"
"grant execute on filter function startswith(string, string, boolean) to public;\n"
"create function sys.endswith(x string, y string)\n"
"returns boolean external name str.endswith;\n"
"grant execute on function endswith(string, string) to public;\n"
"create function sys.endswith(x string, y string, icase boolean)\n"
"returns boolean external name str.endswith;\n"
"grant execute on function endswith(string, string, boolean) to public;\n"
"create filter function sys.endswith(x string, y string)\n"
"external name str.endswith;\n"
"grant execute on filter function endswith(string, string) to public;\n"
"create filter function sys.endswith(x string, y string, icase boolean)\n"
"external name str.endswith;\n"
"grant execute on filter function endswith(string, string, boolean) to public;\n"
"create function sys.contains(x string, y string)\n"
"returns boolean external name str.contains;\n"
"grant execute on function contains(string, string) to public;\n"
"create function sys.contains(x string, y string, icase boolean)\n"
"returns boolean external name str.contains;\n"
"grant execute on function contains(string, string, boolean) to public;\n"
"create filter function sys.contains(x string, y string)\n"
"external name str.contains;\n"
"grant execute on filter function contains(string, string) to public;\n"
"create filter function sys.contains(x string, y string, icase boolean)\n"
"external name str.contains;\n"
"grant execute on filter function contains(string, string, boolean) to public;\n"
"create aggregate sys.group_concat(str string) returns string with order\n"
"	external name \"aggr\".\"str_group_concat\";\n"
"GRANT EXECUTE ON AGGREGATE sys.group_concat(string) TO PUBLIC;\n"
"create aggregate sys.group_concat(str string, sep string) returns string with order\n"
"	external name \"aggr\".\"str_group_concat\";\n"
"GRANT EXECUTE ON AGGREGATE sys.group_concat(string, string) TO PUBLIC;\n"
"create function sys.normalize_monetdb_url(u string)\n"
"returns string external name sql.normalize_monetdb_url;\n"
"grant execute on function sys.normalize_monetdb_url(string) to public;\n"
"create aggregate sha1(val string)\n"
"returns string with order external name aggr.sha1;\n"
"grant execute on aggregate sha1 to public;\n"
"create aggregate sha224(val string)\n"
"returns string with order external name aggr.sha224;\n"
"grant execute on aggregate sha224 to public;\n"
"create aggregate sha256(val string)\n"
"returns string with order external name aggr.sha256;\n"
"grant execute on aggregate sha256 to public;\n"
"create aggregate sha384(val string)\n"
"returns string with order external name aggr.sha384;\n"
"grant execute on aggregate sha384 to public;\n"
"create aggregate sha512(val string)\n"
"returns string with order external name aggr.sha512;\n"
"grant execute on aggregate sha512 to public;\n"
"create aggregate ripemd160(val string)\n"
"returns string with order external name aggr.ripemd160;\n"
"grant execute on aggregate ripemd160 to public;\n"
"create function to_hex(n int)\n"
"returns text external name \"calc\".\"to_hex\";\n"
"grant execute on function to_hex(int) to public;\n"
"create function to_hex(n bigint)\n"
"returns text external name \"calc\".\"to_hex\";\n"
"grant execute on function to_hex(bigint) to public;\n"
};
#include "monetdb_config.h"
#include "sql_import.h"
#ifdef _MSC_VER
#undef read
#pragma section(".CRT$XCU",read)
#endif
LIB_STARTUP_FUNC(init_49_strings_sql)
{ sql_register("49_strings", _49_strings_sql); }
