unsigned char _91_information_schema_sql[23994] = {
"CREATE SCHEMA INFORMATION_SCHEMA;\n"
"COMMENT ON SCHEMA INFORMATION_SCHEMA IS 'ISO/IEC 9075-11 SQL/Schemata';\n"
"CREATE VIEW INFORMATION_SCHEMA.CHARACTER_SETS AS SELECT\n"
"  cast(NULL AS varchar(1)) AS CHARACTER_SET_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS CHARACTER_SET_SCHEMA,\n"
"  cast('UTF-8' AS varchar(16)) AS CHARACTER_SET_NAME,\n"
"  cast('ISO/IEC 10646:2021' AS varchar(20)) AS CHARACTER_REPERTOIRE,\n"
"  cast('UTF-8' AS varchar(16)) AS FORM_OF_USE,\n"
"  cast(NULL AS varchar(1)) AS DEFAULT_COLLATE_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS DEFAULT_COLLATE_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS DEFAULT_COLLATE_NAME;\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.CHARACTER_SETS TO PUBLIC WITH GRANT OPTION;\n"
"CREATE VIEW INFORMATION_SCHEMA.SCHEMATA AS SELECT\n"
"  cast(NULL AS varchar(1)) AS CATALOG_NAME,\n"
"  s.\"name\" AS SCHEMA_NAME,\n"
"  a.\"name\" AS SCHEMA_OWNER,\n"
"  cast(NULL AS varchar(1)) AS DEFAULT_CHARACTER_SET_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS DEFAULT_CHARACTER_SET_SCHEMA,\n"
"  cast('UTF-8' AS varchar(16)) AS DEFAULT_CHARACTER_SET_NAME,\n"
"  cast(NULL AS varchar(1)) AS SQL_PATH,\n"
"  s.\"id\" AS schema_id,\n"
"  s.\"system\" AS is_system,\n"
"  cm.\"remark\" AS comments\n"
" FROM sys.\"schemas\" s\n"
" INNER JOIN sys.\"auths\" a ON s.\"owner\" = a.\"id\"\n"
" LEFT OUTER JOIN sys.\"comments\" cm ON s.\"id\" = cm.\"id\"\n"
" ORDER BY s.\"name\";\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.SCHEMATA TO PUBLIC WITH GRANT OPTION;\n"
"CREATE VIEW INFORMATION_SCHEMA.TABLES AS SELECT\n"
"  cast(NULL AS varchar(1)) AS TABLE_CATALOG,\n"
"  s.\"name\" AS TABLE_SCHEMA,\n"
"  t.\"name\" AS TABLE_NAME,\n"
"  tt.\"table_type_name\" AS TABLE_TYPE,\n"
"  cast(NULL AS varchar(1)) AS SELF_REFERENCING_COLUMN_NAME,\n"
"  cast(NULL AS varchar(1)) AS REFERENCE_GENERATION,\n"
"  cast(NULL AS varchar(1)) AS USER_DEFINED_TYPE_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS USER_DEFINED_TYPE_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS USER_DEFINED_TYPE_NAME,\n"
"  cast(sys.ifthenelse((t.\"type\" IN (0, 3, 7, 20, 30) AND t.\"access\" IN (0, 2)), 'YES', 'NO') AS varchar(3)) AS IS_INSERTABLE_INTO,\n"
"  cast('NO' AS varchar(3)) AS IS_TYPED,\n"
"  cast((CASE t.\"commit_action\" WHEN 1 THEN 'DELETE' WHEN 2 THEN 'PRESERVE' WHEN 3 THEN 'DROP' ELSE NULL END) AS varchar(10)) AS COMMIT_ACTION,\n"
"  t.\"schema_id\" AS schema_id,\n"
"  t.\"id\" AS table_id,\n"
"  t.\"type\" AS table_type_id,\n"
"  st.\"count\" AS row_count,\n"
"  t.\"system\" AS is_system,\n"
"  sys.ifthenelse(t.\"type\" IN (1, 11, 21, 31), TRUE, FALSE) AS is_view,\n"
"  t.\"query\" AS query_def,\n"
"  cm.\"remark\" AS comments\n"
" FROM sys.\"tables\" t\n"
" INNER JOIN sys.\"schemas\" s ON t.\"schema_id\" = s.\"id\"\n"
" INNER JOIN sys.\"table_types\" tt ON t.\"type\" = tt.\"table_type_id\"\n"
" LEFT OUTER JOIN sys.\"comments\" cm ON t.\"id\" = cm.\"id\"\n"
" LEFT OUTER JOIN (SELECT DISTINCT \"schema\", \"table\", \"count\" FROM sys.\"statistics\"()) st ON (s.\"name\" = st.\"schema\" AND t.\"name\" = st.\"table\")\n"
" ORDER BY s.\"name\", t.\"name\";\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.TABLES TO PUBLIC WITH GRANT OPTION;\n"
"CREATE VIEW INFORMATION_SCHEMA.VIEWS AS SELECT\n"
"  cast(NULL AS varchar(1)) AS TABLE_CATALOG,\n"
"  s.\"name\" AS TABLE_SCHEMA,\n"
"  t.\"name\" AS TABLE_NAME,\n"
"  t.\"query\" AS VIEW_DEFINITION,\n"
"  cast('NONE' AS varchar(10)) AS CHECK_OPTION,\n"
"  cast('NO' AS varchar(3)) AS IS_UPDATABLE,\n"
"  cast('NO' AS varchar(3)) AS INSERTABLE_INTO,\n"
"  cast('NO' AS varchar(3)) AS IS_TRIGGER_UPDATABLE,\n"
"  cast('NO' AS varchar(3)) AS IS_TRIGGER_DELETABLE,\n"
"  cast('NO' AS varchar(3)) AS IS_TRIGGER_INSERTABLE_INTO,\n"
"  t.\"schema_id\" AS schema_id,\n"
"  t.\"id\" AS table_id,\n"
"  t.\"type\" AS table_type_id,\n"
"  t.\"system\" AS is_system,\n"
"  cm.\"remark\" AS comments\n"
" FROM sys.\"tables\" t\n"
" INNER JOIN sys.\"schemas\" s ON t.\"schema_id\" = s.\"id\"\n"
" LEFT OUTER JOIN sys.\"comments\" cm ON t.\"id\" = cm.\"id\"\n"
" WHERE t.\"type\" IN (1, 11, 21, 31)\n"
" ORDER BY s.\"name\", t.\"name\";\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.VIEWS TO PUBLIC WITH GRANT OPTION;\n"
"CREATE VIEW INFORMATION_SCHEMA.COLUMNS AS SELECT\n"
"  cast(NULL AS varchar(1)) AS TABLE_CATALOG,\n"
"  s.\"name\" AS TABLE_SCHEMA,\n"
"  t.\"name\" AS TABLE_NAME,\n"
"  c.\"name\" AS COLUMN_NAME,\n"
"  cast(1 + c.\"number\" AS int) AS ORDINAL_POSITION,\n"
"  c.\"default\" AS COLUMN_DEFAULT,\n"
"  cast(sys.ifthenelse(c.\"null\", 'YES', 'NO') AS varchar(3)) AS IS_NULLABLE,\n"
"  cast(sys.\"sql_datatype\"(c.\"type\", c.\"type_digits\", c.\"type_scale\", true, true) AS varchar(1024)) AS DATA_TYPE,\n"
"  cast(sys.ifthenelse(c.\"type\" IN ('varchar','clob','char','json','url','xml') AND c.\"type_digits\" > 0, c.\"type_digits\", NULL) AS int) AS CHARACTER_MAXIMUM_LENGTH,\n"
"  cast(sys.ifthenelse(c.\"type\" IN ('varchar','clob','char','json','url','xml') AND c.\"type_digits\" > 0, 4 * cast(c.\"type_digits\" as bigint), NULL) AS bigint) AS CHARACTER_OCTET_LENGTH,\n"
"  cast(sys.ifthenelse(c.\"type\" IN ('int','smallint','tinyint','bigint','hugeint','float','real','double','decimal','numeric','oid'), c.\"type_digits\", NULL) AS int) AS NUMERIC_PRECISION,\n"
"  cast(sys.ifthenelse(c.\"type\" IN ('int','smallint','tinyint','bigint','hugeint','float','real','double','oid'), 2, sys.ifthenelse(c.\"type\" IN ('decimal','numeric'), 10, NULL)) AS int) AS NUMERIC_PRECISION_RADIX,\n"
"  cast(sys.ifthenelse(c.\"type\" IN ('int','smallint','tinyint','bigint','hugeint','float','real','double','decimal','numeric','oid'), c.\"type_scale\", NULL) AS int) AS NUMERIC_SCALE,\n"
"  cast(sys.ifthenelse(c.\"type\" IN ('date','timestamp','timestamptz','time','timetz'), sys.ifthenelse(c.\"type_scale\" > 0, c.\"type_scale\" -1, 0), NULL) AS int) AS DATETIME_PRECISION,\n"
"  cast(sys.ifthenelse(c.\"type\" IN ('day_interval','month_interval','sec_interval'), sys.\"sql_datatype\"(c.\"type\", c.\"type_digits\", c.\"type_scale\", true, true), NULL) AS varchar(40)) AS INTERVAL_TYPE,\n"
"  cast(CASE c.\"type\" WHEN 'day_interval' THEN 0 WHEN 'month_interval' THEN 0 WHEN 'sec_interval' THEN (sys.ifthenelse(c.\"type_digits\" IN (7, 10, 12, 13), sys.ifthenelse(c.\"type_scale\" > 0, c.\"type_scale\", 3), 0)) ELSE NULL END AS int) AS INTERVAL_PRECISION,\n"
"  cast(NULL AS varchar(1)) AS CHARACTER_SET_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS CHARACTER_SET_SCHEMA,\n"
"  cast(sys.ifthenelse(c.\"type\" IN ('varchar','clob','char','json','url','xml'), 'UTF-8', NULL) AS varchar(16)) AS CHARACTER_SET_NAME,\n"
"  cast(NULL AS varchar(1)) AS COLLATION_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS COLLATION_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS COLLATION_NAME,\n"
"  cast(NULL AS varchar(1)) AS DOMAIN_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS DOMAIN_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS DOMAIN_NAME,\n"
"  cast(NULL AS varchar(1)) AS UDT_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS UDT_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS UDT_NAME,\n"
"  cast(NULL AS varchar(1)) AS SCOPE_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS SCOPE_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS SCOPE_NAME,\n"
"  cast(NULL AS int) AS MAXIMUM_CARDINALITY,\n"
"  cast(NULL AS varchar(1)) AS DTD_IDENTIFIER,\n"
"  cast('NO' AS varchar(3)) AS IS_SELF_REFERENCING,\n"
"  cast(sys.ifthenelse(seq.\"name\" IS NULL OR c.\"null\", 'NO', 'YES') AS varchar(3)) AS IS_IDENTITY,\n"
"  seq.\"name\" AS IDENTITY_GENERATION,\n"
"  seq.\"start\" AS IDENTITY_START,\n"
"  seq.\"increment\" AS IDENTITY_INCREMENT,\n"
"  seq.\"maxvalue\" AS IDENTITY_MAXIMUM,\n"
"  seq.\"minvalue\" AS IDENTITY_MINIMUM,\n"
"  cast(sys.ifthenelse(seq.\"name\" IS NULL, NULL, sys.ifthenelse(seq.\"cycle\", 'YES', 'NO')) AS varchar(3)) AS IDENTITY_CYCLE,\n"
"  cast(sys.ifthenelse(seq.\"name\" IS NULL, 'NO', 'YES') AS varchar(3)) AS IS_GENERATED,\n"
"  cast(sys.ifthenelse(seq.\"name\" IS NULL, NULL, c.\"default\") AS varchar(1024)) AS GENERATION_EXPRESSION,\n"
"  cast('NO' AS varchar(3)) AS IS_SYSTEM_TIME_PERIOD_START,\n"
"  cast('NO' AS varchar(3)) AS IS_SYSTEM_TIME_PERIOD_END,\n"
"  cast('NO' AS varchar(3)) AS SYSTEM_TIME_PERIOD_TIMESTAMP_GENERATION,\n"
"  cast(sys.ifthenelse(t.\"type\" IN (0,3,7,20,30), 'YES', 'NO') AS varchar(3)) AS IS_UPDATABLE,\n"
"  cast(NULL AS varchar(1)) AS DECLARED_DATA_TYPE,\n"
"  cast(NULL AS int) AS DECLARED_NUMERIC_PRECISION,\n"
"  cast(NULL AS int) AS DECLARED_NUMERIC_SCALE,\n"
"  t.\"schema_id\" AS schema_id,\n"
"  c.\"table_id\" AS table_id,\n"
"  c.\"id\" AS column_id,\n"
"  seq.\"id\" AS sequence_id,\n"
"  t.\"system\" AS is_system,\n"
"  cm.\"remark\" AS comments\n"
" FROM sys.\"columns\" c\n"
" INNER JOIN sys.\"tables\" t ON c.\"table_id\" = t.\"id\"\n"
" INNER JOIN sys.\"schemas\" s ON t.\"schema_id\" = s.\"id\"\n"
" LEFT OUTER JOIN sys.\"comments\" cm ON c.\"id\" = cm.\"id\"\n"
" LEFT OUTER JOIN sys.\"sequences\" seq ON ((seq.\"name\"||'\"') = substring(c.\"default\", 3 + sys.\"locate\"('\".\"seq_',c.\"default\",14)))\n"
" ORDER BY s.\"name\", t.\"name\", c.\"number\";\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.COLUMNS TO PUBLIC WITH GRANT OPTION;\n"
"CREATE VIEW INFORMATION_SCHEMA.CHECK_CONSTRAINTS AS SELECT\n"
"  cast(NULL AS varchar(1)) AS CONSTRAINT_CATALOG,\n"
"  s.\"name\" AS CONSTRAINT_SCHEMA,\n"
"  k.\"name\" AS CONSTRAINT_NAME,\n"
"  cast(sys.check_constraint(s.\"name\", k.\"name\") AS varchar(2048)) AS CHECK_CLAUSE,\n"
"  t.\"schema_id\" AS schema_id,\n"
"  t.\"id\" AS table_id,\n"
"  t.\"name\" AS table_name,\n"
"  k.\"id\" AS key_id\n"
" FROM (SELECT sk.\"id\", sk.\"table_id\", sk.\"name\" FROM sys.\"keys\" sk WHERE sk.\"type\" = 4 UNION ALL SELECT tk.\"id\", tk.\"table_id\", tk.\"name\" FROM tmp.\"keys\" tk WHERE tk.\"type\" = 4) k\n"
" INNER JOIN (SELECT st.\"id\", st.\"schema_id\", st.\"name\" FROM sys.\"_tables\" st UNION ALL SELECT tt.\"id\", tt.\"schema_id\", tt.\"name\" FROM tmp.\"_tables\" tt) t ON k.\"table_id\" = t.\"id\"\n"
" INNER JOIN sys.\"schemas\" s ON t.\"schema_id\" = s.\"id\"\n"
" ORDER BY s.\"name\", t.\"name\", k.\"name\";\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.CHECK_CONSTRAINTS TO PUBLIC WITH GRANT OPTION;\n"
"CREATE VIEW INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS SELECT\n"
"  cast(NULL AS varchar(1)) AS CONSTRAINT_CATALOG,\n"
"  s.\"name\" AS CONSTRAINT_SCHEMA,\n"
"  k.\"name\" AS CONSTRAINT_NAME,\n"
"  cast(NULL AS varchar(1)) AS TABLE_CATALOG,\n"
"  s.\"name\" AS TABLE_SCHEMA,\n"
"  t.\"name\" AS TABLE_NAME,\n"
"  cast(CASE k.\"type\" WHEN 0 THEN 'PRIMARY KEY' WHEN 1 THEN 'UNIQUE' WHEN 2 THEN 'FOREIGN KEY' WHEN 3 THEN 'UNIQUE NULLS NOT DISTINCT' WHEN 4 THEN 'CHECK' ELSE NULL END AS varchar(26)) AS CONSTRAINT_TYPE,\n"
"  cast('NO' AS varchar(3)) AS IS_DEFERRABLE,\n"
"  cast('NO' AS varchar(3)) AS INITIALLY_DEFERRED,\n"
"  cast('YES' AS varchar(3)) AS ENFORCED,\n"
"  t.\"schema_id\" AS schema_id,\n"
"  t.\"id\" AS table_id,\n"
"  k.\"id\" AS key_id,\n"
"  k.\"type\" AS key_type,\n"
"  t.\"system\" AS is_system\n"
" FROM (SELECT sk.\"id\", sk.\"table_id\", sk.\"name\", sk.\"type\" FROM sys.\"keys\" sk UNION ALL SELECT tk.\"id\", tk.\"table_id\", tk.\"name\", tk.\"type\" FROM tmp.\"keys\" tk) k\n"
" INNER JOIN (SELECT st.\"id\", st.\"schema_id\", st.\"name\", st.\"system\" FROM sys.\"_tables\" st UNION ALL SELECT tt.\"id\", tt.\"schema_id\", tt.\"name\", tt.\"system\" FROM tmp.\"_tables\" tt) t ON k.\"table_id\" = t.\"id\"\n"
" INNER JOIN sys.\"schemas\" s ON t.\"schema_id\" = s.\"id\"\n"
" ORDER BY s.\"name\", t.\"name\", k.\"name\";\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.TABLE_CONSTRAINTS TO PUBLIC WITH GRANT OPTION;\n"
"CREATE VIEW INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS SELECT\n"
"  cast(NULL AS varchar(1)) AS CONSTRAINT_CATALOG,\n"
"  s.\"name\" AS CONSTRAINT_SCHEMA,\n"
"  fk.\"name\" AS CONSTRAINT_NAME,\n"
"  cast(NULL AS varchar(1)) AS UNIQUE_CONSTRAINT_CATALOG,\n"
"  uks.\"name\" AS UNIQUE_CONSTRAINT_SCHEMA,\n"
"  uk.\"name\" AS UNIQUE_CONSTRAINT_NAME,\n"
"  cast('FULL' AS varchar(7)) AS MATCH_OPTION,\n"
"  fk.\"update_action\" AS UPDATE_RULE,\n"
"  fk.\"delete_action\" AS DELETE_RULE,\n"
"  t.\"schema_id\" AS fk_schema_id,\n"
"  t.\"id\" AS fk_table_id,\n"
"  t.\"name\" AS fk_table_name,\n"
"  fk.\"id\" AS fk_key_id,\n"
"  ukt.\"schema_id\" AS uc_schema_id,\n"
"  uk.\"table_id\" AS uc_table_id,\n"
"  ukt.\"name\" AS uc_table_name,\n"
"  uk.\"id\" AS uc_key_id\n"
" FROM sys.\"fkeys\" fk\n"
" INNER JOIN sys.\"tables\" t ON t.\"id\" = fk.\"table_id\"\n"
" INNER JOIN sys.\"schemas\" s ON s.\"id\" = t.\"schema_id\"\n"
" LEFT OUTER JOIN sys.\"keys\" uk ON uk.\"id\" = fk.\"rkey\"\n"
" LEFT OUTER JOIN sys.\"tables\" ukt ON ukt.\"id\" = uk.\"table_id\"\n"
" LEFT OUTER JOIN sys.\"schemas\" uks ON uks.\"id\" = ukt.\"schema_id\"\n"
" ORDER BY s.\"name\", t.\"name\", fk.\"name\";\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS TO PUBLIC WITH GRANT OPTION;\n"
"CREATE VIEW INFORMATION_SCHEMA.ROUTINES AS SELECT\n"
"  cast(NULL AS varchar(1)) AS SPECIFIC_CATALOG,\n"
"  s.\"name\" AS SPECIFIC_SCHEMA,\n"
"  cast(f.\"name\"||'('||f.\"id\"||')' AS varchar(270)) AS SPECIFIC_NAME,\n"
"  cast(NULL AS varchar(1)) AS ROUTINE_CATALOG,\n"
"  s.\"name\" AS ROUTINE_SCHEMA,\n"
"  f.\"name\" AS ROUTINE_NAME,\n"
"  ft.\"function_type_keyword\" AS ROUTINE_TYPE,\n"
"  cast(NULL AS varchar(1)) AS MODULE_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS MODULE_SCHEMA,\n"
"  cast(f.\"mod\" AS varchar(128)) AS MODULE_NAME,\n"
"  cast(NULL AS varchar(1)) AS UDT_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS UDT_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS UDT_NAME,\n"
"  cast(CASE f.\"type\" WHEN 1 THEN sys.\"sql_datatype\"(a.\"type\", a.\"type_digits\", a.\"type_scale\", true, true) WHEN 2 THEN NULL WHEN 5 THEN 'TABLE' WHEN 7 THEN 'TABLE' ELSE NULL END AS varchar(1024)) AS DATA_TYPE,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('varchar','clob','char','json','url','xml') AND a.\"type_digits\" > 0, a.\"type_digits\", NULL) AS int) AS CHARACTER_MAXIMUM_LENGTH,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('varchar','clob','char','json','url','xml') AND a.\"type_digits\" > 0, 4 * cast(a.\"type_digits\" as bigint), NULL) AS bigint) AS CHARACTER_OCTET_LENGTH,\n"
"  cast(NULL AS varchar(1)) AS CHARACTER_SET_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS CHARACTER_SET_SCHEMA,\n"
"  'UTF-8' AS CHARACTER_SET_NAME,\n"
"  cast(NULL AS varchar(1)) AS COLLATION_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS COLLATION_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS COLLATION_NAME,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('int','smallint','tinyint','bigint','hugeint','float','real','double','decimal','numeric','oid'), a.\"type_digits\", NULL) AS int) AS NUMERIC_PRECISION,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('int','smallint','tinyint','bigint','hugeint','float','real','double','oid'), 2, sys.ifthenelse(a.\"type\" IN ('decimal','numeric'), 10, NULL)) AS int) AS NUMERIC_PRECISION_RADIX,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('int','smallint','tinyint','bigint','hugeint','float','real','double','decimal','numeric','oid'), a.\"type_scale\", NULL) AS int) AS NUMERIC_SCALE,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('date','timestamp','timestamptz','time','timetz'), a.\"type_scale\" -1, NULL) AS int) AS DATETIME_PRECISION,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('day_interval','month_interval','sec_interval'), sys.\"sql_datatype\"(a.\"type\", a.\"type_digits\", a.\"type_scale\", true, true), NULL) AS varchar(40)) AS INTERVAL_TYPE,\n"
"  cast(CASE a.\"type\" WHEN 'day_interval' THEN 0 WHEN 'month_interval' THEN 0 WHEN 'sec_interval' THEN (sys.ifthenelse(a.\"type_digits\" IN (7, 10, 12, 13), sys.ifthenelse(a.\"type_scale\" > 0, a.\"type_scale\", 3), 0)) ELSE NULL END AS int) AS INTERVAL_PRECISION,\n"
"  cast(NULL AS varchar(1)) AS TYPE_UDT_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS TYPE_UDT_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS TYPE_UDT_NAME,\n"
"  cast(NULL AS varchar(1)) AS SCOPE_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS SCOPE_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS SCOPE_NAME,\n"
"  cast(NULL AS int) AS MAXIMUM_CARDINALITY,\n"
"  cast(NULL AS int) AS DTD_IDENTIFIER,\n"
"  cast(sys.\"ifthenelse\"(sys.\"locate\"('begin',f.\"func\") > 0, sys.\"ifthenelse\"(sys.\"endswith\"(f.\"func\",';'), sys.\"substring\"(f.\"func\", sys.\"locate\"('begin',f.\"func\"), sys.\"length\"(sys.\"substring\"(f.\"func\", sys.\"locate\"('begin',f.\"func\")))-1), sys.\"substring\"(f.\"func\", sys.\"locate\"('begin',f.\"func\"))), NULL) AS varchar(8196)) AS ROUTINE_BODY,\n"
"  f.\"func\" AS ROUTINE_DEFINITION,\n"
"  cast(sys.\"ifthenelse\"(sys.\"locate\"('external name',f.\"func\") > 0, sys.\"ifthenelse\"(sys.\"endswith\"(f.\"func\",';'), sys.\"substring\"(f.\"func\", 14 + sys.\"locate\"('external name',f.\"func\"), sys.\"length\"(sys.\"substring\"(f.\"func\", 14 + sys.\"locate\"('external name',f.\"func\")))-1), sys.\"substring\"(f.\"func\", 14 + sys.\"locate\"('external name',f.\"func\"))), NULL) AS varchar(1024)) AS EXTERNAL_NAME,\n"
"  fl.\"language_keyword\" AS EXTERNAL_LANGUAGE,\n"
"  'GENERAL' AS PARAMETER_STYLE,\n"
"  'YES' AS IS_DETERMINISTIC,\n"
"  cast(sys.ifthenelse(f.\"side_effect\", 'MODIFIES', 'READ') AS varchar(10)) AS SQL_DATA_ACCESS,\n"
"  cast(CASE f.\"type\" WHEN 2 THEN NULL ELSE 'NO' END AS varchar(3)) AS IS_NULL_CALL,\n"
"  cast(NULL AS varchar(1)) AS SQL_PATH,\n"
"  cast(NULL AS varchar(1)) AS SCHEMA_LEVEL_ROUTINE,\n"
"  cast(NULL AS int) AS MAX_DYNAMIC_RESULT_SETS,\n"
"  cast(NULL AS varchar(1)) AS IS_USER_DEFINED_CAST,\n"
"  cast(NULL AS varchar(1)) AS IS_IMPLICITLY_INVOCABLE,\n"
"  cast(NULL AS varchar(1)) AS SECURITY_TYPE,\n"
"  cast(NULL AS varchar(1)) AS TO_SQL_SPECIFIC_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS TO_SQL_SPECIFIC_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS TO_SQL_SPECIFIC_NAME,\n"
"  cast(NULL AS varchar(1)) AS AS_LOCATOR,\n"
"  cast(NULL AS timestamp) AS CREATED,\n"
"  cast(NULL AS timestamp) AS LAST_ALTERED,\n"
"  cast(NULL AS varchar(1)) AS NEW_SAVEPOINT_LEVEL,\n"
"  cast(NULL AS varchar(1)) AS IS_UDT_DEPENDENT,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_FROM_DATA_TYPE,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_AS_LOCATOR,\n"
"  cast(NULL AS int) AS RESULT_CAST_CHAR_MAX_LENGTH,\n"
"  cast(NULL AS int) AS RESULT_CAST_CHAR_OCTET_LENGTH,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_CHAR_SET_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_CHAR_SET_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_CHARACTER_SET_NAME,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_COLLATION_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_COLLATION_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_COLLATION_NAME,\n"
"  cast(NULL AS int) AS RESULT_CAST_NUMERIC_PRECISION,\n"
"  cast(NULL AS int) AS RESULT_CAST_NUMERIC_RADIX,\n"
"  cast(NULL AS int) AS RESULT_CAST_NUMERIC_SCALE,\n"
"  cast(NULL AS int) AS RESULT_CAST_DATETIME_PRECISION,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_INTERVAL_TYPE,\n"
"  cast(NULL AS int) AS RESULT_CAST_INTERVAL_PRECISION,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_TYPE_UDT_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_TYPE_UDT_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_TYPE_UDT_NAME,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_SCOPE_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_SCOPE_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_SCOPE_NAME,\n"
"  cast(NULL AS int) AS RESULT_CAST_MAX_CARDINALITY,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_DTD_IDENTIFIER,\n"
"  cast(NULL AS varchar(1)) AS DECLARED_DATA_TYPE,\n"
"  cast(NULL AS int) AS DECLARED_NUMERIC_PRECISION,\n"
"  cast(NULL AS int) AS DECLARED_NUMERIC_SCALE,\n"
"  cast(NULL AS varchar(1)) AS RESULT_CAST_FROM_DECLARED_DATA_TYPE,\n"
"  cast(NULL AS int) AS RESULT_CAST_DECLARED_NUMERIC_PRECISION,\n"
"  cast(NULL AS int) AS RESULT_CAST_DECLARED_NUMERIC_SCALE,\n"
"  f.\"schema_id\" AS schema_id,\n"
"  f.\"id\" AS function_id,\n"
"  f.\"type\" AS function_type,\n"
"  f.\"language\" AS function_language,\n"
"  f.\"system\" AS is_system,\n"
"  cm.\"remark\" AS comments\n"
" FROM sys.\"functions\" f\n"
" INNER JOIN sys.\"schemas\" s ON s.\"id\" = f.\"schema_id\"\n"
" INNER JOIN sys.\"function_types\" ft ON ft.\"function_type_id\" = f.\"type\"\n"
" INNER JOIN sys.\"function_languages\" fl ON fl.\"language_id\" = f.\"language\"\n"
" LEFT OUTER JOIN sys.\"args\" a ON a.\"func_id\" = f.\"id\" and a.\"inout\" = 0 and a.\"number\" = 0\n"
" LEFT OUTER JOIN sys.\"comments\" cm ON cm.\"id\" = f.\"id\"\n"
" WHERE f.\"type\" in (1, 2, 5, 7)\n"
" ORDER BY s.\"name\", f.\"name\";\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.ROUTINES TO PUBLIC WITH GRANT OPTION;\n"
"CREATE VIEW INFORMATION_SCHEMA.PARAMETERS AS SELECT\n"
"  cast(NULL AS varchar(1)) AS SPECIFIC_CATALOG,\n"
"  s.\"name\" AS SPECIFIC_SCHEMA,\n"
"  cast(f.\"name\"||'('||f.\"id\"||')' AS varchar(270)) AS SPECIFIC_NAME,\n"
"  cast(sys.ifthenelse((a.\"inout\" = 0 OR f.\"type\" = 2), 1 + a.\"number\", sys.ifthenelse(f.\"type\" = 1, a.\"number\", (1 + a.\"number\" - f.count_out_cols))) AS int) AS ORDINAL_POSITION,\n"
"  cast(sys.ifthenelse(a.\"inout\" = 0, 'OUT', sys.ifthenelse(a.\"inout\" = 1, 'IN', 'INOUT')) as varchar(5)) AS PARAMETER_MODE,\n"
"  cast(sys.ifthenelse(a.\"inout\" = 0, 'YES', 'NO') as varchar(3)) AS IS_RESULT,\n"
"  cast(NULL AS varchar(1)) AS AS_LOCATOR,\n"
"  a.\"name\" AS PARAMETER_NAME,\n"
"  cast(NULL AS varchar(1)) AS FROM_SQL_SPECIFIC_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS FROM_SQL_SPECIFIC_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS FROM_SQL_SPECIFIC_NAME,\n"
"  cast(NULL AS varchar(1)) AS TO_SQL_SPECIFIC_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS TO_SQL_SPECIFIC_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS TO_SQL_SPECIFIC_NAME,\n"
"  cast(sys.\"sql_datatype\"(a.\"type\", a.\"type_digits\", a.\"type_scale\", true, true) AS varchar(1024)) AS DATA_TYPE,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('varchar','clob','char','json','url','xml') AND a.\"type_digits\" > 0, a.\"type_digits\", NULL) AS int) AS CHARACTER_MAXIMUM_LENGTH,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('varchar','clob','char','json','url','xml') AND a.\"type_digits\" > 0, 4 * cast(a.\"type_digits\" as bigint), NULL) AS bigint) AS CHARACTER_OCTET_LENGTH,\n"
"  cast(NULL AS varchar(1)) AS CHARACTER_SET_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS CHARACTER_SET_SCHEMA,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('varchar','clob','char','json','url','xml'), 'UTF-8', NULL) AS varchar(16)) AS CHARACTER_SET_NAME,\n"
"  cast(NULL AS varchar(1)) AS COLLATION_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS COLLATION_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS COLLATION_NAME,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('int','smallint','tinyint','bigint','hugeint','float','real','double','decimal','numeric','oid'), a.\"type_digits\", NULL) AS int) AS NUMERIC_PRECISION,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('int','smallint','tinyint','bigint','hugeint','float','real','double','oid'), 2, sys.ifthenelse(a.\"type\" IN ('decimal','numeric'), 10, NULL)) AS int) AS NUMERIC_PRECISION_RADIX,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('int','smallint','tinyint','bigint','hugeint','float','real','double','decimal','numeric','oid'), a.\"type_scale\", NULL) AS int) AS NUMERIC_SCALE,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('date','timestamp','timestamptz','time','timetz'), sys.ifthenelse(a.\"type_scale\" > 0, a.\"type_scale\" -1, 0), NULL) AS int) AS DATETIME_PRECISION,\n"
"  cast(sys.ifthenelse(a.\"type\" IN ('day_interval','month_interval','sec_interval'), sys.\"sql_datatype\"(a.\"type\", a.\"type_digits\", a.\"type_scale\", true, true), NULL) AS varchar(40)) AS INTERVAL_TYPE,\n"
"  cast(CASE a.\"type\" WHEN 'day_interval' THEN 0 WHEN 'month_interval' THEN 0 WHEN 'sec_interval' THEN (sys.ifthenelse(a.\"type_digits\" IN (7, 10, 12, 13), sys.ifthenelse(a.\"type_scale\" > 0, a.\"type_scale\", 3), 0)) ELSE NULL END AS int) AS INTERVAL_PRECISION,\n"
"  cast(NULL AS varchar(1)) AS UDT_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS UDT_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS UDT_NAME,\n"
"  cast(NULL AS varchar(1)) AS SCOPE_CATALOG,\n"
"  cast(NULL AS varchar(1)) AS SCOPE_SCHEMA,\n"
"  cast(NULL AS varchar(1)) AS SCOPE_NAME,\n"
"  cast(NULL AS int) AS MAXIMUM_CARDINALITY,\n"
"  cast(NULL AS varchar(1)) AS DTD_IDENTIFIER,\n"
"  cast(NULL AS varchar(1)) AS DECLARED_DATA_TYPE,\n"
"  cast(NULL AS int) AS DECLARED_NUMERIC_PRECISION,\n"
"  cast(NULL AS int) AS DECLARED_NUMERIC_SCALE,\n"
"  cast(NULL AS varchar(1)) AS PARAMETER_DEFAULT,\n"
"  f.\"schema_id\" AS schema_id,\n"
"  f.\"id\" AS function_id,\n"
"  a.\"id\" AS arg_id,\n"
"  f.\"name\" AS function_name,\n"
"  f.\"type\" AS function_type,\n"
"  f.\"system\" AS is_system\n"
" FROM sys.\"args\" a\n"
" INNER JOIN (SELECT fun.id, fun.schema_id, fun.name, fun.type, fun.system, (select count(*) from sys.args a0 where a0.inout = 0 and a0.func_id = fun.id) as count_out_cols FROM sys.\"functions\" fun WHERE fun.\"type\" in (1, 2, 5, 7)) f ON f.\"id\" = a.\"func_id\"\n"
" INNER JOIN sys.\"schemas\" s ON s.\"id\" = f.\"schema_id\"\n"
" ORDER BY s.\"name\", f.\"name\", f.\"id\", a.\"inout\" DESC, a.\"number\";\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.PARAMETERS TO PUBLIC WITH GRANT OPTION;\n"
"CREATE VIEW INFORMATION_SCHEMA.SEQUENCES AS SELECT\n"
"  cast(NULL AS varchar(1)) AS SEQUENCE_CATALOG,\n"
"  s.\"name\" AS SEQUENCE_SCHEMA,\n"
"  sq.\"name\" AS SEQUENCE_NAME,\n"
"  cast('BIGINT' AS varchar(16)) AS DATA_TYPE,\n"
"  cast(64 AS SMALLINT) AS NUMERIC_PRECISION,\n"
"  cast(2 AS SMALLINT) AS NUMERIC_PRECISION_RADIX,\n"
"  cast(0 AS SMALLINT) AS NUMERIC_SCALE,\n"
"  sq.\"start\" AS START_VALUE,\n"
"  sq.\"minvalue\" AS MINIMUM_VALUE,\n"
"  sq.\"maxvalue\" AS MAXIMUM_VALUE,\n"
"  sq.\"increment\" AS INCREMENT,\n"
"  cast(sys.ifthenelse(sq.\"cycle\", 'YES', 'NO') AS varchar(3)) AS CYCLE_OPTION,\n"
"  cast(NULL AS varchar(16)) AS DECLARED_DATA_TYPE,\n"
"  cast(NULL AS SMALLINT) AS DECLARED_NUMERIC_PRECISION,\n"
"  cast(NULL AS SMALLINT) AS DECLARED_NUMERIC_SCALE,\n"
"  sq.\"schema_id\" AS schema_id,\n"
"  sq.\"id\" AS sequence_id,\n"
"  get_value_for(s.\"name\", sq.\"name\") AS current_value,\n"
"  sq.\"cacheinc\" AS cacheinc,\n"
"  cm.\"remark\" AS comments\n"
" FROM sys.\"sequences\" sq\n"
" INNER JOIN sys.\"schemas\" s ON sq.\"schema_id\" = s.\"id\"\n"
" LEFT OUTER JOIN sys.\"comments\" cm ON sq.\"id\" = cm.\"id\"\n"
" ORDER BY s.\"name\", sq.\"name\";\n"
"GRANT SELECT ON TABLE INFORMATION_SCHEMA.SEQUENCES TO PUBLIC WITH GRANT OPTION;\n"
};
#include "monetdb_config.h"
#include "sql_import.h"
#ifdef _MSC_VER
#undef read
#pragma section(".CRT$XCU",read)
#endif
LIB_STARTUP_FUNC(init_91_information_schema_sql)
{ sql_register("91_information_schema", _91_information_schema_sql); }
